### ISSUE TITLE
enable scenario generation

### ISSUE THREAD

**Issue by DvirHaberman** [DvirHaberman/Development#51]
#### Needs to edit js to enable functionality for:
- [x] run or run and generate button according to is generate check box
- [x] enable or disable geneare menu with is generate check box
- [x] show where scenario will be generated
- [ ] web worker for monitoring generation process (call monitor function with generate id - icons, gray = not yet, orange = partial success, red = fail, green = success)
- [ ] call generate backend function with generate button
- [ ] call genearte and run backend function with generate & run button
- [x] clear generate menu when stage is loaded / new stage

#### need to update html to:
- [ ] show progress of generating process

for now use dummy functions

**Comment by ilan-github** [comment]
"advance button" - somehow the small-margin is not execute
Run & Generate Buttun - need to add the </i> ..

**Comment by ilan-github** [comment]
when we press on "Run Stage" // "Run and Generate" .. (i think that if we are in "New" we need to do "Save" first).

**Comment by DvirHaberman** [comment]
@ilan-github
change run to disable at "New"
