### ISSUE TITLE
Create get run mission and generate mission dummys

### ISSUE THREAD

**Issue by ilan-github** [DvirHaberman/Development#57]
**/dummyapi/RunMission/get_by_id/X**
returns RunMission status: 
{ general_status:0 - error 1 - good,
  generate_mission: null if none was linked
                                { id,
                                  validation : {status, amount, total} status - 0 - did not start, 1-failed, 2-partial success, 3- success, 4- inprocess
                                  db_updates: {status, amount, total},
                                  generation: {status, amount, total}
run_status: {status, amount, total}
is_done: true/false

/dummyapi/GenerateMission/get_by_id/X
id,
validation : {status, amount, total} status - 0 - did not start, 1-failed, 2-partial success, 3- success
db_updates: {status, amount, total},
generation: {status, amount, total}
is_done: true/false
}
run_status : generation: {status, amount, total}
is_done: true/false

**Comment by DvirHaberman** [comment]
done
@ilan-github

**Comment by ilan-github** [comment]
מעולה
